name: 'Rootless devenv.sh Nix ARC Setup'
description: 'Setup devenv, including cacheing'
inputs: {}
outputs: {}

runs:
  using: "composite"
  steps:
    - id: cache
      uses: nix-community/cache-nix-action@a75bbceef596ef10719eb9cb6821120a05022126 # v5
      with:
        primary-key: nix-${{ hashFiles('devenv.*') }}

    - name: Base setup (if cache missed)
      if: steps.cache.outputs.hit-primary-key != 'true'
      shell: bash
      run: |
        cp -r /nix/store_base/* /nix/store
        # Cleanup (prevents base from ending up in cache)
        find /nix/store_base -type d -exec chmod 777 {} +
        rm -rf /nix/store_base
        
    - name: Setup devenv
      shell: bash
      run: nix profile install nixpkgs#devenv

    