name: 'Rootless devenv.sh Nix ARC Setup'
description: 'Setup devenv, including cacheing'
inputs: {}
outputs: {}

runs:
  using: "node20"
  main: "src/main.mjs"
  post: "src/post.mjs"
  post-if: "success()"
    