name: 'Rootless devenv.sh Nix ARC Setup'
description: 'Setup devenv, including cacheing'
inputs: {}
outputs: {}

runs:
  using: "composite"
  steps:
    - id: cache
      uses: nix-community/cache-nix-action@8351fb9f51c580c96c509987ebb99e38aed956ce # v5
      with:
        primary-key: nix-${{ hashFiles('devenv.*') }}

    - name: Base setup (if cache missed)
      if: steps.cache.outputs.hit-primary-key != 'true'
      shell: bash
      run: |
        cp -r /nix_base/store/* /nix/store
        
    - name: Setup devenv
      shell: bash
      run: nix profile install nixpkgs#devenv

    